### ISSUE TITLE
"Built 0 css files in …" even when > 0 files were built

### ISSUE THREAD

**Issue by quinncomendant** [paulcpederson/scss-cli#5]
I noticed scss-cli will often say zero files were built, even when some were indeed built:

    Built 0 css files in 226ms with 0 errors

This doesn't always occur; sometimes it correctly reports the number of files that were built. It is intermittent. 

The problem seems to be in using the `count` variable with `async-foreach`. I added this at line 80 of scss-cli/bin/cli.js to print the `count` increment:

    count++
    console.log(count)

Then I noticed in cases when the script reported zero files built, the `console.log(count)` output would be printed *after* the "Built…" message, like this:

    Built 0 css files in 233ms with 0 errors
    1

In cases when it correctly reported the number of files built, like this:

    1
    Built 1 css files in 229ms with 0 errors

I think this means async-foreach's "done" callback is firing before the foreach has actually completed. I'm not familiar with async-foreach, so I'm not sure if this is a bug there, or an implementation error.

**Comment by quinncomendant** [comment]
It works well with a hackity hack =\

    setTimeout(function () {
        var summary = 'Built ' + count + ' css files in ' + (t1 - t0) + 'ms with ' + errors + ' errors:'
        console.log(color.green(summary))
    }, 50);

**Comment by paulcpederson** [comment]
@quinncomendant this is interesting. I think it is an implementation problem. I'll look into this.

**Comment by paulcpederson** [comment]
@quinncomendant since [multiple-file compilation](https://github.com/sass/node-sass/pull/838) landed in node-sass I don't think I'm going to trouble shoot this. Closing now, feel free to reopen if need be!

**Comment by quinncomendant** [comment]
@paulcpederson, understood: if node-sass has the desired functionality, then no need to support a secondary project.

In case you're curious, I learned the correct solution to this issue is promises. Here's a good article on them: https://www.promisejs.org/
