### ISSUE TITLE
Doesn't recursively add files

### ISSUE THREAD

**Issue by talwoolf** [paulcpederson/scss-cli#6]
Sorry just realised I made a mistake and this seems to be fine. 

Would be amazing though if you could implement a way to pipe the content streams on. maybe a --pipe argument which will pipe the contents instead of writing them using your writeFile method. That would be really helpful especially to enable autoprefixing.

Great work though, really nice and very helpful tool.

**Comment by paulcpederson** [comment]
@talwoolf the pr I did on node-sass will work as you describe. So after the next version is released you'll be able to do just that! :+1:
